- name: capture zombie processes
  shell: ps axl | awk '{ if ($10 ~ /Z/) print $0 }'
  register: zombie_processes

- name: capture D states processes
  shell: ps axl | awk '{ if ($10 ~ /D/) print $0 }'
  register: D_processes

- name: Set facts for zombie and D processes
  set_fact:
    zombie_process_list: "{{ zombie_processes.stdout_lines }}"
    D_process_list: "{{ D_processes.stdout_lines }}"


- name: Check if Zombie or process in D states exists
  assert:
    that:
      - zombie_process_list | length == 0 and D_process_list | length == 0
    fail_msg: "zombie or processes in D states found in {{ inventory_hostname }}."
    success_msg: "No zombie or processes in D states found in {{ inventory_hostname }}."