---
# tasks file for roles/cluster-state
- name: import cluster status tasks
  import_tasks: cluster-status-task.yaml
  tags:
    - capture-cluster-state
  when: inventory_hostname in groups['primary-master']  
   
